[package]
name = "game-temp-1"
version = "0.1.0"
authors = ["Vladimir <azuresplash@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "*", features = [ "dynamic"] }
anyhow = "1"
